### ISSUE TITLE
Docs a soooooo slow. Look into a screenshot

### ISSUE THREAD

**Issue by isnifer** [date-fns/date-fns.org#105]
![image](https://user-images.githubusercontent.com/1788245/31850834-880dae1e-b662-11e7-9883-17025e16449c.png)

**Comment by kossnocorp** [comment]
@isnifer please describe what you did before it started hanging and how long the site was opened.

**Comment by isnifer** [comment]
@kossnocorp just opened site from the 1st second

**Comment by kossnocorp** [comment]
Try to open the site with all extensions disabled. I suspect that this is caused by one of your extensions.

**Comment by isnifer** [comment]
So, yes. It works as expected in Incognito mode.

**Comment by isnifer** [comment]
But it strange anyway, cause any other site works as expected with them.

**Comment by kossnocorp** [comment]
It could be "React-Sight" or something React-related. If you're brave enough you can enable that extension one-by-one to identify the problematic extension and connect with the author of the leaking extension.

**Comment by isnifer** [comment]
@kossnocorp correct. I've removed React-Sight and problem was solved.

**Comment by kossnocorp** [comment]
👍
