### ISSUE TITLE
CDN / SSL Error: NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by jus101** [date-fns/date-fns.org#113]
Hi,

I'm getting an SSL error when I try to load https://cdn.date-fns.org/v1.9.0/date_fns.min.js using Chrome (66).

"This server could not prove that it is cdn.date-fns.org; its security certificate is from *.cloudfront.net. This may be caused by a misconfiguration or an attacker intercepting your connection."

**Comment by kossnocorp** [comment]
Hey, the CDN server and CDN version of the library isn't officially supported anymore. But you still can use a version maintained by cdnjs.com: https://cdnjs.com/libraries/date-fns.
