### ISSUE TITLE
Website uses an out-of-date version of dateFns

### ISSUE THREAD

**Issue by wcauchois** [date-fns/date-fns.org#124]
Hello,

It looks like date-fns.org uses a different version of date-fns than the version that's installed by NPM. I'm not sure how to determine the version used there, but in the chrome web inspector I can see the modules are using the snake_case naming convention (i.e. `add_minutes/index.js)` which means that it at least dates from before this [fairly old SHA](https://github.com/date-fns/date-fns/commit/ce7e9bb926986804a30a643ff5deec5c790b2e95#diff-48ae116d2b61efbf97366513a9f41adf) that changes the naming convention to camelCase.

![image](https://user-images.githubusercontent.com/300544/49386810-5f84fb00-f6ee-11e8-9412-30076c2ce94b.png)

I understand there seems to be a new version of date-fns in development and maybe you don't want to include an unstable version on the website, but the version that you install by default from NPM seems to be fairly different from the one included on the website which is very confusing. I was using the website to try out date-fns and noticed a discrepancy in behavior which is how I noticed this issue.

Thanks!

**Comment by torgeir** [comment]
Just spent a good hour before arriving here, concluding that [this was not working correctly even after being successfully merged](https://github.com/date-fns/date-fns/issues/465) - only to find that I had been testing an old release of `date-fns` in the developer console of the date-fns.org website..

I definitely second this issue. I was quite surprised to find an out of date version running on the projects main site.

**Comment by kossnocorp** [comment]
Sorry, everyone. I've disabled the REPL to avoid further confusion. If someone is willing to help with bringing it back, you're more than welcome.

**Comment by TheMoonDawg** [comment]
Ah, well that explains I can't find _any_ version on the docs site now! Would love to see it added back in at some point. It definitely helps with experimentation.
