### ISSUE TITLE
Add date format playground

### ISSUE THREAD

**Issue by notiv-nt** [date-fns/date-fns.org#141]
On the page https://date-fns.org/v2.2.1/docs/format just above `Accepted patterns` or to the right in empty space, It would be convenient to see the current date in the entered format

Small `input`(format) -> `output`(current date in entered format)

**Comment by leshakoss** [comment]
Now this functionality is essentially available though #176. It's less convenient, sure, but good enough for now. PRs for this idea are still welcome, but I'm closing the issue for cleaning purposes
