### ISSUE TITLE
Wrong link to the post about the new API of format in v2

### ISSUE THREAD

**Issue by stof** [date-fns/date-fns.org#143]
The 2.0 changelog has a link to https://blog.date-fns.org/post/unicode-tokens-in-date-fns-v2-sreatyki91jg for more details on the new format string API. But this link does not work.

**Comment by dkozickis** [comment]
Thank you for all your Symfony and PHP related work @stof!

@kossnocorp you wanna have a look? Seems to be down for some time already.

**Comment by leshakoss** [comment]
The link works now!
