### ISSUE TITLE
 Example output is incorrect

### ISSUE THREAD

**Issue by lramosduarte** [date-fns/date-fns.org#154]
The output for `endOfDay` example are wrong. [Doc](https://date-fns.org/v2.11.1/docs/endOfDay)

This sample:
```javascript
// The end of a day for 2 September 2014 11:55:00:
var result = endOfDay(new Date(2014, 8, 2, 11, 55, 0))
//=> Tue Sep 02 2014 23:59:59.999
```
should be like this:
```
// The end of a day for 2 September 2014 11:55:00:
var result = endOfDay(new Date(2014, 9, 2, 11, 55, 0))
//=> Tue Sep 02 2014 23:59:59.999
```
or:
```
// The end of a day for 2 August 2014 11:55:00:
var result = endOfDay(new Date(2014, 9, 2, 11, 55, 0))
//=> Tue Sep 02 2014 23:59:59.999
```

**Comment by dkozickis** [comment]
Month in `new Date` constructor is zero indexed. As in 
January is 0, September is 8, hence the example is correct :) 

Reference here - http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date
