### ISSUE TITLE
Make functions avaliable on website console

### ISSUE THREAD

**Issue by JuanchiRios** [date-fns/date-fns.org#156]
There is a closed issue date-fns/date-fns#701 for this.
I found this to be really useful. As a workaround, I'm using pages like https://stackblitz.com/edit/date-fns-playground but it's not the same.

**Comment by kossnocorp** [comment]
Sorry about that! I had to remove this feature because it didn't consider the selected version. v1 and v2 are very different, and it confused people. Also, v2 doesn't have a UMD build. I didn't have time to add it back, and nobody volunteered to help.

**Comment by JuanchiRios** [comment]
@kossnocorp 
I can do it but I will need some guidance. Is there any better way to contact you?

**Comment by adpirz** [comment]
@JuanchiRios Did you end up picking this up?

If not, @kossnocorp, would be happy to help reintroduce this -- we use `date-fns` heavily and also found tinkering with it in the console useful

**Comment by leshakoss** [comment]
Duplicates #144. Working on it in #176

**Comment by deathemperor** [comment]
not sure if I should post here but the feature is broken for awhile now. got this error running `init()` 

![image](https://github.com/date-fns/date-fns.org/assets/4255482/e89d5335-50db-478f-8e3e-a1aab008218f)

**Comment by kossnocorp** [comment]
@deathemperor thank you for the comment, yeah the latest `2.30.0` version doesn't work well with ESM, so I just locked `2.29.3` until v3 is shipped.

**Comment by deathemperor** [comment]
> @deathemperor thank you for the comment, yeah the latest `2.30.0` version doesn't work well with ESM, so I just locked `2.29.3` until v3 is shipped.

appreciate the support. It helps. I set up this func in our local development for ease of API test and now it works with `v2.29.3` locked in
