### ISSUE TITLE
Strange situation with the z-index of the .docs_nav_bar element

### ISSUE THREAD

**Issue by anzome** [date-fns/date-fns.org#167]
I see how the elements of the code snippets overlap the navigation bar because it has `{z-index: 1}`. That is not enough to put the navigation bar high enough. But at the same time I see that, within source code, the element has proper value for the z-index: 100.

I've checked build scripts and found there no obvious explanation of how the 100 became 1. There are also other styles that have different values for this element. It means that probably, the site deployed not from the master branch. Further digging requires some information about the details of the deployment process.

**Comment by leshakoss** [comment]
I believe this is not an issue anymore b/c we are using a completely new css-in-js stack now. But please let me know if you encounter the issue again
