### ISSUE TITLE
[ERROR: doc site cannot show page]

### ISSUE THREAD

**Issue by OhIAmFine** [date-fns/date-fns.org#174]
doc site show the errors and cannot show the guidelines
![Kapture 2021-01-13 at 15 36 28](https://user-images.githubusercontent.com/10390004/104420815-69f46d00-55b5-11eb-9519-2eb26ff607dc.gif)

**Comment by tan75** [comment]
@OhIAmFine 
are you still facing this issue? If so, please provide the name of your ISP and the browser you are using.

**Comment by tan75** [comment]
Hello,
closing this call as all the docs are available in our source code via JSDoc e.g.:
[addDays JSDoc](https://github.com/date-fns/date-fns/blob/master/src/addDays/index.ts#L5-L26)
