### ISSUE TITLE
Docs site not working.

### ISSUE THREAD

**Issue by articleten-andy** [date-fns/date-fns.org#175]
https://date-fns.org/docs/

Doesn't work any more, it just says "Failed to load package list!"

**Comment by articleten-andy** [comment]
In Chrome yes it's still doing it, even in an Incognito window with no extensions running. Edge does seem to have started working now interestingly, but just checked Firefox and now I get the message there, when previously it had been working...

It says "Loading" for a few seconds then "Failed to load Package List" and in the console it says...

[2021-02-02T13:12:53.434Z]  @firebase/firestore: Firestore (8.2.2): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

My ISP is "EE" in the UK.

**Comment by sskasim** [comment]
I have the same issue today with Chrome and Edge. It says "Loading" for a few seconds then "Failed to load Package List"

**Comment by tan75** [comment]
> I have the same issue today with Chrome and Edge. It says "Loading" for a few seconds then "Failed to load Package List"

@sskasim 
What is your ISP and location?

**Comment by sskasim** [comment]
> > I have the same issue today with Chrome and Edge. It says "Loading" for a few seconds then "Failed to load Package List"
> 
> @sskasim
> What is your ISP and location?

I am working from home. My ISP is Entouch in Richmond Texas

**Comment by m-jung** [comment]
I was facing the same issue using Firefox 87 and Chrome 92.
While any of the requested endpoints (including google-analytics and droubleclick) seemed to respond, it was the GET request to [https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?...](https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?database=projects%2Fdate-fns-org%2Fdatabases%2F(default)) that timed out and lead to "Failed to load package list!".
The keep-alive POST to the same endpoint worked.

For me it was my companies VPN, that seemed to cause the problem. With VPN disabled, the Docs were accessible.
Even though there might be something wrong with the VPN, the "whole internet" works perfectly.

**Comment by SarahFowler73** [comment]
I can access on my Boston-based VPN, but cannot from my New York Verizon Fios Network.

**Comment by tan75** [comment]
hi all,
all the docs are available in our source code via JSDoc e.g.:

[addDays JSDoc](https://github.com/date-fns/date-fns/blob/master/src/addDays/index.ts#L5-L26)

**Comment by andrew-mcgregor** [comment]
HI, i have this too.  It's seems the doubleclick.com is causing the issue as adverts are blocked by my network.  Is there any chance of removing this?

**Comment by ShanArosh** [comment]
Why's this keeps happening

**Comment by ElyasAsmad** [comment]
Documentation website is down.

![image](https://github.com/date-fns/date-fns.org/assets/78308067/7099b859-7783-4228-88bb-00dd8ad4a576)

Tried to use Microsoft Edge but still got the same result.

My ISP is Unifi and I am trying to access this website from Malaysia

**Comment by ShanArosh** [comment]
For anyone who's looking for another copy of docs , visit https://devdocs.io/date_fns/
