### ISSUE TITLE
Documentation pages are not loading and website is down

### ISSUE THREAD

**Issue by tkdphoenix** [date-fns/date-fns.org#179]
I have tried multiple ways to get to a page in documentation for date-fns with no success. When I go to this address: https://date-fns.org/v2.16.1/docs or this address: https://date-fns.org/v2.16.1/docs/getMonth I get the message "Failed to load package list!". Please review

**Comment by tkdphoenix** [comment]
I am in Phoenix, Arizona, USA and my ISP is Cox Cable. Now docs show a 404.

**Comment by leshakoss** [comment]
Duplicate of #175

**Comment by y471n** [comment]
Encountering same problem from India today.

**Comment by Davydx7** [comment]
Having the same issue. Located in Nigeria

**Comment by The-CodeNinja** [comment]
+1 from India

**Comment by rafaelbpa** [comment]
Same here. Can't see the docs right now. Tried every browser...

**Comment by JRixGeromo** [comment]
Same here. Can't see the docs right now. Tried every browser too...

**Comment by The-CodeNinja** [comment]
Using Safari worked for me

**Comment by pedro-mass** [comment]
Happening again today... Is there a status page?

**Comment by hisreal123** [comment]
is there a fix to this yet, I've been tryingg this for an hr+, anyone got a way into the doc. i need help with that. Thanks

**Comment by ScorpyG** [comment]
Hey guys, still experiencing this issue when trying to access `https://date-fns.org/docs/Getting-Started`. The landing page seems fine.

I tried on `Brave v1.69.160` & `Safari` with and without the VPN. Does anyone else still have this issue?

**Comment by hisreal123** [comment]
The page is working now without VPN.

**Comment by ScorpyG** [comment]
@hisreal123 Maybe this is just an issue with my mac... Not sure if this is replicable.

![Screenshot 2024-09-03 at 2 45 08 PM](https://github.com/user-attachments/assets/41e37e08-1c2b-4cd8-b868-38a89a38f063)

**Comment by githero20** [comment]
https://date-fns.org/docs/Getting-Started

Same for me, doesn't open and this is not the first time. I believe it could be an ISP thing, trying to access the site from Nigeria.
