### ISSUE TITLE
Docs broken

### ISSUE THREAD

**Issue by AndrewBerry** [date-fns/date-fns.org#200]
The docs website (https://date-fns.org/docs/Getting-Started) is displaying the following error:

    Failed to load package list!

**Comment by tan75** [comment]
Hi all,
the docs website is fully operational however sometimes it is being blocked by a VPN as it runs from Firebase.
If you can't access the docs website, please use our Github repo as all the docs are available via JSDocs annotations e.g.
[Add function](https://github.com/date-fns/date-fns/blob/master/src/add/index.ts#L8)
Hope this helps!
