### ISSUE TITLE
The documentation page is offline

### ISSUE THREAD

**Issue by toydaboss** [date-fns/date-fns.org#212]
I can't access the website for the documentation using the URL, https://date-fns.org/

**Comment by tan75** [comment]
@toydaboss 
the doc website is up and running, however sometimes it can't be accessed in some regions as it is running from Firebase.

All the docs are available in our source code via JSDoc e.g.:

[addDays JSDoc](https://github.com/date-fns/date-fns/blob/master/src/addDays/index.ts#L5-L26)
