### ISSUE TITLE
`blockquote` style for light theme is unreadable / poor contrast

### ISSUE THREAD

**Issue by fturmel** [date-fns/date-fns.org#220]
![CleanShot 2024-03-30 at 08 57 33@2x](https://github.com/date-fns/date-fns.org/assets/4009209/60a2702b-d439-4500-94b5-1cecfab56ecd)

**Comment by RushilJalal** [comment]
duplicate as #217 already exists

**Comment by fturmel** [comment]
oof I guess I missed it, thanks!
