### ISSUE TITLE
When viewing documentation, left to the header should be logo

### ISSUE THREAD

**Issue by LeshaKoss** [date-fns/date-fns.org#4]
![screen shot 2015-10-21 at 12 33 33](https://cloud.githubusercontent.com/assets/566319/10629412/09e8be80-77e8-11e5-9a35-dd526952d00d.png)
smth like this but less shitty and logo purple
Logo should be a link to the main page

**Comment by kossnocorp** [comment]
@LeshaKoss don't worry about the design. Just ping me when you done and I'll adjust it.

**Comment by kossnocorp** [comment]
Also label is not needed, just a logo.
