### ISSUE TITLE
Style markdown ordered lists

### ISSUE THREAD

**Issue by LeshaKoss** [date-fns/date-fns.org#68]
https://github.com/date-fns/date-fns/blob/master/CONTRIBUTING.md#getting-started
https://date-fns.org/docs/Contributing#getting-started

**Comment by kossnocorp** [comment]
It's parsed, but styles are missing:

<img width="952" alt="fullscreen_11_05_16_09_05" src="https://cloud.githubusercontent.com/assets/52201/15169321/8f5b63a6-1757-11e6-8165-8146066463ba.png">
