### ISSUE TITLE
Add `dateFns` object to global scope on date-fns.org

### ISSUE THREAD

**Issue by paraboom** [date-fns/date-fns.org#90]
Sometimes it's super useful to try some functions right on the `date-fns.org` website. The easiest way to do this - make available `dateFns` object in global scope. Every developer could just open a console of the browser, try and combine any functions.

For example, `https://lodash.com/` has global `_` object on their website and I often use it.

**Comment by paraboom** [comment]
Any updates here?

**Comment by LeshaKoss** [comment]
@paraboom oops 😬

Deployed
![screen shot 2016-11-23 at 19 55 18](https://cloud.githubusercontent.com/assets/566319/20564296/ca6a561a-b1b6-11e6-9e40-9f3b62dee997.png)

**Comment by paraboom** [comment]
Wow! Thanks a lot!

**Comment by LeshaKoss** [comment]
No problem 🙂
