### ISSUE TITLE
Scroll behavior is weird when navigating

### ISSUE THREAD

**Issue by stof** [date-fns/date-fns.org#92]
When navigating to a different doc page after having scrolled the current page (which is a common use case when reading the doc), the right panel keeps its scroll position after updating its content. This is very confusing because it forces to scroll up to be able to start reading the new content.
I suggest scrolling to top again when switching page.

I'm using Firefox in case this is browser-specific.

**Comment by DeMuu** [comment]
It's not browser-specific, I just checked with Chrome. It's not really obvious as there are a lot of items with only little content or if you have a big screen but it's a good point in my opinion.

I can take a look at this if approved. @kossnocorp what do you think?

**Comment by leshakoss** [comment]
I believe this bug is fixed for quite some time :)
