### ISSUE TITLE
Looking for testimonials for the new home page

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns.org#93]
New home page is coming! We're looking for real testimonials from the users. If you want to share good or bad, please reply here or ping me directly.

![date fns modern javascript date utility library](https://cloud.githubusercontent.com/assets/52201/21388486/6e6ecf3e-c774-11e6-8a0f-729fa360aedb.png)

**Comment by jrop** [comment]
> `date-fns` is the modular path to date/time manipulation.  Where I work, it helped us get our bundle sizes down, especially because we are able to include only the functionality we need.

**Comment by MiracleBlue** [comment]
Date-fns gave us the power to work directly with date objects, without worrying about conversion or mutations.  It's a real game changer for dates.

**Comment by kossnocorp** [comment]
@jrop @MiracleBlue thank you, guys!

**Comment by MiracleBlue** [comment]
My pleasure!  Sad to see it was only us 2 :( but I'm happy to help as much as I can!

**Comment by pke** [comment]
Will contribute once our app is converted from `momentjs`. Build size is the single most important factor for us.
