### ISSUE TITLE
Links to English locale in /docs/I18n is broken

### ISSUE THREAD

**Issue by jsyrjala** [date-fns/date-fns.org#98]
English locale links on https://date-fns.org/docs/I18n point to https://github.com/date-fns/date-fns/tree/master/src/locale/en which gives 404.

They should point to https://github.com/date-fns/date-fns/tree/master/src/locale/en-US instead?

**Comment by fehergeri13** [comment]
Its still broken

**Comment by leshakoss** [comment]
Fixed now :)
